query SearchAds(
  $skip: Int
  $take: Int
  $tagIds: String
  $title: String
  $categoryId: Int
  $ownerId: Int
) {
  ads(
    skip: $skip
    take: $take
    tagIds: $tagIds
    title: $title
    categoryId: $categoryId
    ownerId: $ownerId
  ) {
    list {
      title
      picture
      price
      id
    }
    totalCount
  }
}
