services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
      
  backend:
    depends_on:
      db:
        condition: service_healthy
    build: 
      context: backend
      dockerfile: Dockerfile.production
    
    ports:
      - 4001:4001

  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile.production
    ports:
      - 3000:3000
