name: "integration-tests"

on:
  pull_request:
  workflow_call:

jobs:
  check_changes_back:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          paths: '["backend/**"]'
  integration-tests:
    needs: check_changes_back
    if: needs.check_changes_back.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Make envfile
        run: cp .env.example .env
      - name: Install deps
        run: npm ci
      - name: Start test DB
        run: npm run testDB:wait
      - name: Run tests
        run: npm test
